services:
  - type: web
    name: floodguard-bd
    env: python
    buildCommand: pip install -r requirements.txt && python train_real_model.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    autoDeploy: true
